name: Telegram Push Alert

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build message and send to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          SHORT_REF: ${{ github.ref_name }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

          COMMIT_COUNT=$(jq '.commits | length' "$GITHUB_EVENT_PATH")
          PUSHER=$(jq -r '.pusher.name // .pusher.username // .pusher.email' "$GITHUB_EVENT_PATH")
          [ -z "$PUSHER" ] && PUSHER="$ACTOR"
          BRANCH="$SHORT_REF"
          REPO_URL="https://github.com/$REPO"

          if [ "$COMMIT_COUNT" -gt 0 ]; then
            COMMIT_LINES=$(jq -r '.commits[] | "- " + (.author.name // .author.username // "unknown") + ": " + (.message|gsub("\n";" ")) + " (" + .url + ")"' "$GITHUB_EVENT_PATH" | sed ':a;N;$!ba;s/\n/%0A/g')
          else
            COMMIT_LINES="(no commits payload)"
          fi

          MSG="🚀 *${PUSHER}* pushed *${COMMIT_COUNT}* commit(s) to *${REPO}* on branch *${BRANCH}*%0A%0A${COMMIT_LINES}%0A%0A🔗 ${REPO_URL}/tree/${BRANCH}"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${MSG}" \
            -d parse_mode="Markdown"
